rvm: 
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
notifications:
  email:
    - inkblot@movealong.org
env:
  - PUPPET_VERSION=3.0.0
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=3.2.0
  - PUPPET_VERSION=3.3.0
  - PUPPET_VERSION=3.4.0
  - PUPPET_VERSION=3.5.0
  - PUPPET_VERSION=3.6.0
  - PUPPET_VERSION=3.7.0
